// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVOYYTAkbz9HfnVOUPQouldEyLNNh09U4',
    appId: '1:109927738124:web:d61f22de118079ec88b729',
    messagingSenderId: '109927738124',
    projectId: 'video-call-ea4a5',
    authDomain: 'video-call-ea4a5.firebaseapp.com',
    storageBucket: 'video-call-ea4a5.appspot.com',
    measurementId: 'G-SH12TYHT0Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfhzUoA3_L_YfPxdp7cQaM_YBmgWsCsNg',
    appId: '1:109927738124:android:567a905422bd270288b729',
    messagingSenderId: '109927738124',
    projectId: 'video-call-ea4a5',
    storageBucket: 'video-call-ea4a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCffT43DJ05JPNMobN2YHTB22oysmfz9wg',
    appId: '1:109927738124:ios:a5681e9d9e7ccdc888b729',
    messagingSenderId: '109927738124',
    projectId: 'video-call-ea4a5',
    storageBucket: 'video-call-ea4a5.appspot.com',
    iosBundleId: 'com.app.pairme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCffT43DJ05JPNMobN2YHTB22oysmfz9wg',
    appId: '1:109927738124:ios:e838aecf18e7d11388b729',
    messagingSenderId: '109927738124',
    projectId: 'video-call-ea4a5',
    storageBucket: 'video-call-ea4a5.appspot.com',
    iosBundleId: 'com.example.pairMe.RunnerTests',
  );
}
